### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by NKruszewska** [iitis/polymer_entropy#17]
As  we are planning what to present in the manuscript I want to share here two proposition and ask for advice (mainly @Piotr8706 and  @kdomino) which one is most valuable to use. It turned out that there are two approaches and we earlier didnt notice that:
a) as it is done now by @soycapitan: one histogram per 2 columns (so it is 24 histograms for 1-4 angles and 23 hist. for 1-3 angles). Then entropy is presented as a function of number of mer (number of column). We have then 60 such entropy charts (2 chains * 10 realisations * 3 ions). 
I have problem to analyze this. Because readers could be interested why the entropy for similar angles are different - it is the same angles between the same chemical groups. Maybe this is because of the proximity to some amino acids of albumin, ect.  We are short in time so such analyzis is hard to be done. But we can see a lot from such charts - it is absolutely worth to study this separeted angles.
b) one histogram per realization; then the entropy chart can be drawn as a function of realization number. Then we can have only 6 entropy charts and we can compare them with binding energy between albumin and chain (HA or CS). In such situation I can compare the results eg. with Hexaire et al. (2000). In such case we lost some information because we are looking on the chain as a whole. We got some "coarse graining". But we are computing also persistence length of the chain - in such case we also looking on the chain as a whole. But there is little risk - we dont know what we will get and if we really be able to compare the results.
@Piotr8706 what did you plan to present at start when you plan this publication?

**Comment by NKruszewska** [comment]
@soycapitan was it done?

**Comment by NKruszewska** [comment]
@soycapitan @kdomino 
I'm pretty sure that the histograms not contain angles from all mers insidde one relisation. I tested it in Excel: I took CS_1 with NaCl and plot two first Psi1-4 (column 8vs9 and column 12vs13 on one plot) and I got:
![image](https://user-images.githubusercontent.com/94965439/164752705-86cf8380-5b80-4f8f-ade6-f7b9eac03afd.png)
On the right it is what we got using your program. Maybe we didn't understand each other what we want to obtain? I wanted to get on X axis col8 + col12 + col16 + ... and on Y axis col9 + col13 + col17 + ... of course one as a function of the second.

**Comment by NKruszewska** [comment]
@soycapitan Thank you! Can I ask you for dumping txt files of the histograms? I still can't understand what we have on the histograms. In the link above you present hist. for CS6_4 with Ca. I took the source file (.tab) and plot only 5 from 24 columns (so 5000 points):
![image](https://user-images.githubusercontent.com/94965439/164947372-11427acd-adce-4fb1-8bd8-96f83fffd050.png)
As you see there are many lost angles. I can't understand what is happen with them.

**Comment by kdomino** [comment]
@NKruszewska @soycapitan I think I understand what is wrong. 1 - on the plot we have  density, so n.o. samples is equal to area of bin x this what is on the color scale. S as we have 100 x 100 bins each is of size 3.6 x 3.6 \approx 13. So the bin with 25 has approx 300 elements. The thinks in circles appears rarely,  so on the slide it may represent to e.g. 0.1 that is not distinguishable from the background.  If you  plot the scatter-plot, you see rare points but you do not see frequency of frequent points. @NKruszewska we had this issue before, about the frequency plot, remember? We end up with strange renormalisation of histograms. 

What I propose:   
- change the slider to the log scale,
- change to normalized histograms, there will be then no problem with counting,
- perhaps if not sufficient distinguish a color of the 0 background on the histograms

**Comment by NKruszewska** [comment]
@kdomino Now I understand everything! Thank you.

**Comment by kdomino** [comment]
@soycapitan we can try first with the log scale

**Comment by kdomino** [comment]
I changes to the log scale, there are following plots.

![Albumin+CS6_1_analysis_Ca_hist2D_ϕ₁₄_ψ₁₄](https://user-images.githubusercontent.com/25100121/165283836-4f840671-9dd3-47cb-a066-4ae61254ceb2.png)

**Comment by NKruszewska** [comment]
@kdomino The plots look similar to previous ones. I still can't see most of the angles (I was looking at the last case CS6_4 Ca). There are for example a lot of positive Psi1-4 and all of them are missed in the plot.

**Comment by NKruszewska** [comment]
@soycapitan @kdomino 
I think I found our angles:
![image](https://user-images.githubusercontent.com/94965439/165366320-d2130c64-51ee-497e-b7a2-b1ab37f85127.png)

I changed:
plt.hist2d(x, y, bins=numbins, range=[[-180,180],[-180,180]], norm=mpl.colors.LogNorm(vmin=0.1, vmax=100), cmap=plt.cm.YlOrRd)
on
plt.hist2d(x_data, y_data, bins=numbins, range=[[-180, 180], [-180, 180]], norm=mpl.colors.LogNorm(vmin=0.1, vmax=100),
cmap=plt.cm.YlOrRd)

Am I right?

**Comment by NKruszewska** [comment]
I think that we don't need this LogNorm(). Without normalization plots look like this:
![image](https://user-images.githubusercontent.com/94965439/165377622-696a09ae-cbba-45a8-83e9-77179daaf9b6.png)

And we were wrong. It is not density - it is the number of angles in each bin. Now sum of all squares is 24k/23k.

**Comment by soycapitan** [comment]
Yes, you are!

Great finding, now the histograms look much more populated. I converted your change recommendation into #34

**Comment by NKruszewska** [comment]
@soycapitan Thank you. My final line is:
res = plt.hist2d(x_data, y_data, bins=numbins, range=[[-180, 180], [-180, 180]], **density=True**, cmap=plt.cm.YlOrRd)

and I used f.write("Sum: "+str(np.sum(res[0]))) to test the results.

**Comment by soycapitan** [comment]
@NKruszewska Thank you. updated #34 - now with your final line and reintroduced scientific notation.


![Albumin+CS6_3_analysis_Mg_hist2D_ϕ₁₄_ψ₁₄](https://user-images.githubusercontent.com/11042812/165437646-a86309d4-f451-4ece-99aa-672d3c830989.png)

**Comment by soycapitan** [comment]
@NKruszewska Thank you. updated #34 - now with your final line and reintroduced scientific notation.


![Albumin+CS6_3_analysis_Mg_hist2D_ϕ₁₄_ψ₁₄](https://user-images.githubusercontent.com/11042812/165437646-a86309d4-f451-4ece-99aa-672d3c830989.png)

**Comment by NKruszewska** [comment]
It looks great now. Thank you.

**Comment by kdomino** [comment]
@NKruszewska so we can close this issue

**Comment by NKruszewska** [comment]
Yes. Closing.
