### ISSUE TITLE
Plot entropy vs. particular ions and angle types

### ISSUE THREAD

**Issue by kdomino** [iitis/polymer_entropy#21]
Plot entropy with percentiles envelopes for particular ions (Na^+, Mg^2+, Ca^2+) and particular angle types (\Phi_14 vs. \Psi_14 and \Phi_13 vs. \Psi_13) f Will have 6 point on the plot for HA and 6 points on the plot for CS. Make 2 plots one for CS6 and one for HA.

**Comment by soycapitan** [comment]
![plot21](https://user-images.githubusercontent.com/11042812/164782556-242448f1-6cfe-4627-a10e-b9166c21b67d.png)

**Comment by kdomino** [comment]
Each entropy should be computed from aggregate hist, and then plot min and max instead of quantiles

**Comment by kdomino** [comment]
Dane, perhaps not yet best presentation, in #41

**Comment by soycapitan** [comment]
As for #42 :
![envelope_analysis_Albumin+CS6](https://user-images.githubusercontent.com/11042812/165613437-374d68ba-b842-40c2-a5dc-7437d03c7cd4.png)

The result is equal to one from #41 but the code is cleaner IMO
