### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by NKruszewska** [iitis/polymer_entropy#38]
@soycapitan @kdomino Does the whole code works for you? I got error with stack trace:
Albumin+HA_8_analysis_Na ϕ₁₃ ψ₁₃
52.916950216818044
Albumin+HA_9_analysis_Na ϕ₁₃ ψ₁₃
53.97289263210509
Traceback (most recent call last):
  File "F:\PycharmProjects\polymer_entropy\src\plot.py", line 75, in <module>
    myData.hist_of_entropy(criteria, "ϕ₁₄ mer 1", "ψ₁₄ mer 1", bincount, args.plotdir)
  File "F:\PycharmProjects\polymer_entropy\src\experiment.py", line 324, in hist_of_entropy
    xcol = chosen_experiments[0].get_colnum_by_meaning(xcolumn)
IndexError: list index out of range

I'm using such parameters: plot.py --datafolder ../data2 --complex 'Albumin+HA'
(I had to modify slightly your datafolder because the folders are by default out of scr folder)

**Comment by kdomino** [comment]
You run it it Windows

**Comment by NKruszewska** [comment]
I took [make_ent_plots](https://github.com/iitis/polymer_entropy/tree/make_ent_plots) branch and run on my Windows with Python 3.9 and I got:
Traceback (most recent call last):
  File "F:\PycharmProjects\polymer_entropy\src\plot.py", line 75, in <module>
    myData.plot_ent_reals(entropy_13_13, entropy_14_14, args, args.plotdir, 10)
  File "F:\PycharmProjects\polymer_entropy\src\experiment.py", line 406, in plot_ent_reals
    entropies1313[k-1] = entropy_13_13[key]
KeyError: "'Albumin+HA'_1_analysis_Ca"

**Comment by soycapitan** [comment]
Most recent PR #42 drops entirely dictionaries like `entropy_13_13` - lets check if this occurs with newer codebase.

**Comment by NKruszewska** [comment]
Snapshot from my debuger:
![image](https://user-images.githubusercontent.com/94965439/165622524-77a1aa3a-759f-46fc-92c4-353a7acfc89f.png)

mycomplex under Windows is getting backslash

**Comment by kdomino** [comment]
I think some description of the code usage will be helpful, splitting onto Linux users and windows users. @soycapitan can you follow it, to issue  #7

**Comment by soycapitan** [comment]
I confirm that the code runs smoothly on my box. Created #47 with steps I take for running.
The problematic variables are no more in the code. @NKruszewska could you confirm that the issue is still valid for Windows?

**Comment by NKruszewska** [comment]
@soycapitan The code works for me excellent.

**Comment by soycapitan** [comment]
I am working on a feature to run this program centrally, on github - then we will not need to run it locally anymore.

**Comment by soycapitan** [comment]
PR #48 provides and describes feature mentioned above.

**Comment by kdomino** [comment]
@NKruszewska I understand it is solved

**Comment by NKruszewska** [comment]
@kdomino Yes. I suppose I can close it.
