### ISSUE TITLE
Limited time series

### ISSUE THREAD

**Issue by NKruszewska** [iitis/polymer_entropy#39]
In albumin+HA realizations, the times of simulation are not equal. It is not strict 100ns (as it is in the case of CS6).
Are you sure that you cut off redundant data on histograms and entropy? I'm asking because on the histograms I see the description:
![image](https://user-images.githubusercontent.com/94965439/165475718-97b89d47-1b9a-4e5d-8598-d113c8e5de02.png)
here 24216. Each realization has a different n.

**Comment by kdomino** [comment]
I observed the same

**Comment by NKruszewska** [comment]
I suppose it influences the entropy. Doesn't it?

**Comment by kdomino** [comment]
slightly in my opinion, as there are 1 per more data, with probably similar frequency distribution.

**Comment by NKruszewska** [comment]
Ok thank you - so let's ignore it this time. But it could be needed in the future.

**Comment by soycapitan** [comment]
Can we close it?

**Comment by NKruszewska** [comment]
Yes, but can you add an annotation to remember about it? We are comparing entropies and when we will have accidentally some of the files with 1000 time-points and some with 2000, the comparison will be not right. The parameter should be added in the future.

**Comment by soycapitan** [comment]
We can keep it on the table with a `wontfix` label for now.
