### ISSUE TITLE
Clear data folders

### ISSUE THREAD

**Issue by kdomino** [iitis/polymer_entropy#43]
Remove ```data``` folder as outdated. Change ```data2``` to ```data_HA``` and data3 to ```data_CS6```.  @NKruszewska @Piotr8706 what do you think, shall we?

**Comment by NKruszewska** [comment]
@kdomino Yes. Please.

**Comment by NKruszewska** [comment]
Now data4 folder contains data_HA.

**Comment by soycapitan** [comment]
would you mind having all data nested under `data` so that we have `data/HA` and `data/CS6` ?

**Comment by kdomino** [comment]
@soycapitan let do it

**Comment by kdomino** [comment]
and remove realization ```11``` and ```12``` as we did before. We had already discussion on it.

**Comment by kdomino** [comment]
so now we should have: ```data4``` -> ```data/HA``` (with ```10``` realisations)  and ```data3``` -> ```data\CS6``` and rest should be removed. @NKruszewska is it right?

**Comment by NKruszewska** [comment]
@kdomino right

**Comment by kdomino** [comment]
OK. @NKruszewska  made a pull request  #46
