### ISSUE TITLE
Font changes

### ISSUE THREAD

**Issue by NKruszewska** [iitis/polymer_entropy#45]
I don't know if you plan to merge branches master and make_ent_plots but I want only to show you differences in plots between the two branches - just in case if you didn't notice it.
![image](https://user-images.githubusercontent.com/94965439/165723505-f609b570-7572-47d8-aee5-548a28325781.png)

**Comment by kdomino** [comment]
@NKruszewska everything is merged into master. Hence use master, and plot will be with larger font what looks better I think

**Comment by kdomino** [comment]
so use master branch for plots

**Comment by NKruszewska** [comment]
Ah - I forgot to ask a question. Is it on purpose? The bigger fonts look better but in this case, we have only 0, 100, -100 on the axes. It can be hard to read it. It is of course nothing and we can do something with it only if a Reviewer says something about it.

**Comment by kdomino** [comment]
smaller looked difficult to read, you can of course make something intermediate

**Comment by NKruszewska** [comment]
thx @kdomino - I'm closing the issue. It was only a question if it is on purpose.
